image: "debian:sid"

.test-template:
  stage: Test
  variables:
    MONGODB_HOST: mongo
  services:
    - mongo:latest
  script:
    - pip3 install nose coverage
    - nosetests -v --with-coverage --cover-tests --cover-package=nokkhum -w tests/*


before_script:
  - apt update
  - apt install -y python3 python3-dev python3-pip watchman
  - python3 --version
  - pip3 install -r requirements.txt
  - python3 setup.py develop


stages:
  - Code Analysis


flake8:
  stage: Code Analysis
  script:
    - pip3 install flake8
    - flake8 --max-line-length=120 nokkhum/*
    - flake8 --max-line-length=120 tests/*


pylint:
  stage: Code Analysis
  allow_failure: true
  script:
    - pip3 install pylint
    - pylint -d C0301 nokkhum/*.py

pyre:
    stage: Code Analysis
    script:
        - pip3 install pyre-check
        - pyre --source-directory nokkhum/*.py check