version: '3'
services:
    mongodb:
        image: mongo
        container_name: nokkhum-mongodb
        volumes:
            - ../deployment/nokkhum/mongodb/data/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
            - default

    stan-server:
        image: nats-streaming
        container_name: nokkhum-stan-server
        volumes:
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
            - default
        command: -cid nokkhum-stan-cluster

    web:
        build: .
        image: nokkhum-image
        container_name: nokkhum-web
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8080:9000
        links:
            - mongodb
            - stan-server
        depends_on:
            - stan-server
            - mongodb
        networks:
            - default
        restart: always
        environment:
            NOKKHUM_SETTINGS: /app/nokkhum-production.cfg
        command: uwsgi --lazy-apps --ini /app/scripts/nokkhum-uwsgi-web.ini

    streaming:
        build: .
        image: nokkhum-image
        container_name: nokkhum-streaming
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8081:8081
        links:
            - mongodb
            - stan-server
        depends_on:
            - stan-server
            - mongodb
        networks:
            - default
        environment:
            NOKKHUM_SETTINGS: /app/nokkhum-production-quart.cfg
            QUART_ENV: production
        restart: always
        # command: uwsgi --lazy-apps --ini /app/scripts/nokkhum-uwsgi-streaming.ini
        command: nokkhum-streaming -d -H 0.0.0.0 -P 8081

    controller:
        build: .
        image: nokkhum-image
        container_name: nokkhum-controller
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        links:
            - mongodb
            - stan-server
        depends_on:
            - stan-server
            - mongodb
        networks:
            - default
        restart: always
        environment:
            NOKKHUM_SETTINGS: /app/nokkhum-production.cfg
        command: nokkhum-controller

    compute:
        build: .
        image: nokkhum-image
        container_name: nokkhum-compute
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        links:
            - stan-server
        depends_on:
            - stan-server
            - controller
        networks:
            - default
        restart: always
        environment:
            NOKKHUM_SETTINGS: /app/nokkhum-production.cfg
        command: nokkhum-compute


networks:
    default:
      
