version: '3'
services:
    mongodb:
        image: mongo
        container_name: nokkhum-mongodb
        volumes:
            - ../deployment/nokkhum/mongodb/data/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
            - default
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    nats-server:
        image: nats
        container_name: nokkhum-nats-server
        volumes:
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
            - default
        command: -js -m 8222
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    web:
        build: .
        image: nokkhum-image
        container_name: nokkhum-web
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8080:9000
        links:
            - mongodb
            - nats-server
        depends_on:
            - nats-server
            - mongodb
        networks:
            - default
        restart: always
        environment:
            NOKKHUM_SETTINGS: /app/nokkhum-production.cfg
        command: uwsgi --lazy-apps --ini /app/scripts/nokkhum-uwsgi-web.ini
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    streaming:
        build: .
        image: nokkhum-image
        container_name: nokkhum-streaming
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8081:8081
        links:
            - mongodb
            - nats-server
        depends_on:
            - nats-server
            - mongodb
        networks:
            - default
        environment:
            NOKKHUM_SETTINGS: /app/nokkhum-production-quart.cfg
            QUART_ENV: production
        restart: always
        # command: uwsgi --lazy-apps --ini /app/scripts/nokkhum-uwsgi-streaming.ini
        command: nokkhum-streaming -d -H 0.0.0.0 -P 8081
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    controller:
        build: .
        image: nokkhum-image
        container_name: nokkhum-controller
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        links:
            - mongodb
            - nats-server
        depends_on:
            - nats-server
            - mongodb
        networks:
            - default
        restart: always
        environment:
            NOKKHUM_SETTINGS: /app/nokkhum-production.cfg
        command: nokkhum-controller
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    compute:
        build: .
        image: nokkhum-image
        container_name: nokkhum-compute
        volumes:
            - ../deployment:/deployment
            - ../deployment/nokkhum/cache:/deployment/nokkhum/cache
            - /etc/localtime:/etc/localtime:ro
        links:
            - nats-server
        depends_on:
            - nats-server
            - controller
        networks:
            - default
        restart: always
        ulimits:
            nofile:
                soft: "65536"
                hard: "65536"
        environment:
            NOKKHUM_SETTINGS: /app/nokkhum-production.cfg
        command: nokkhum-compute
        logging:
            options:
                max-size: "10m"
                max-file: "3"



networks:
    default:
      
