version: '3'
services:
    mongodb:
        image: mongo
        container_name: nokkhum-mongodb
        volumes:
            - ../deployment/nokkhum/mongodb/data/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        # restart: always
        ports:
            - 27017:27017
        networks:
            - default

    tans-server:
        image: nats-streaming
        container_name: nokkhum-tans-server
        volumes:
            - /etc/localtime:/etc/localtime:ro
        # restart: always
        ports:
            - 4222:4222
            - 6222:6222
            - 8222:8222
        networks:
            - default
        command: -cid nokkhum-cluster

    web:
        build: .
        image: nokkhum-image
        container_name: nokkhum-web
        volumes:
            - .:/app
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8080:8080
        links:
            - mongodb
            - tans-server
        depends_on:
            - tans-server
            - mongodb
        networks:
            - default
        # restart: always
        environment:
            NOKKHUM_SETTINGS: /app/nokkhum-development.cfg
            FLASK_ENV: development
            DEBUG: 1
        # command: uwsgi --lazy-apps --ini /app/scripts/nokkhum-uwsgi-web.ini
        command: nokkhum-web -d -H 0.0.0.0 -P 8080

    streaming:
        build: .
        image: nokkhum-image
        container_name: nokkhum-streaming
        volumes:
            - .:/app
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8081:8081
        links:
            - mongodb
            - tans-server
        depends_on:
            - tans-server
            - mongodb
        networks:
            - default
        environment:
            NOKKHUM_SETTINGS: /app/nokkhum-development.cfg
            FLASK_ENV: development
            DEBUG: 1
        # restart: always
        # command: uwsgi --lazy-apps --ini /app/scripts/nokkhum-uwsgi-streaming.ini
        command: nokkhum-streaming -d -H 0.0.0.0 -P 8081

    controller:
        build: .
        image: nokkhum-image
        container_name: nokkhum-controller
        volumes:
            - .:/app
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        links:
            - mongodb
            - tans-server
        depends_on:
            - tans-server
            - mongodb
        networks:
            - default
        restart: always
        environment:
            NOKKHUM_SETTINGS: /app/nokkhum-development.cfg
        # command: nokkhum-controller
        command: nokkhum-controller

    compute:
        build: .
        image: nokkhum-image
        container_name: nokkhum-compute
        volumes:
            - .:/app
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        links:
            - tans-server
        depends_on:
            - tans-server
            - controller
        networks:
            - default
        restart: always
        environment:
            NOKKHUM_SETTINGS: /app/nokkhum-development.cfg
        # command: nokkhum-compute
        command: nokkhum-compute


networks:
    default:
      
